CREATE DATABASE  CSE_3B_310

SELECT * FROM DEPOSIT

-----------------------------------------PART A-------------------------------------------
--1
ALTER TABLE DEPOSIT 
ADD CITY VARCHAR(20) , PINCODE INT;

SELECT * FROM DEPOSIT

--2.
ALTER TABLE DEPOSIT
ALTER COLUMN CNAME VARCHAR(35)

--3
ALTER TABLE DEPOSIT
ALTER COLUMN AMOUNT INT

--4.
EXEC SP_RENAME 'DEPOSIT.ACTNO','ANO';
SELECT * FROM DEPOSIT

--5.
ALTER TABLE DEPOSIT
DROP COLUMN CITY

--6.
EXEC SP_RENAME 'DEPOSIT','DEPOSIT_DETAIL';
SELECT * FROM DEPOSIT_DETAIL


-------------------------------------PART B-------------------------------------

--1
EXEC SP_RENAME 'DEPOSIT_DETAIL.ADATE','AOPENDATE'

--2.
ALTER TABLE DEPOSIT_DETAIL
DROP COLUMN AOPENDATE

--3
EXEC SP_RENAME 'DEPOSIT_DETAIL.CNAME','CUSTOMERNAME'

------------------------------------------ PART C ---------------------------------------------------

CREATE TABLE STUDENT_DETAIL
(
	ENROLLMENT_NO VARCHAR(20),
	NAME VARCHAR(25),
	CPI DECIMAL(5,2),
	BIRTHDATE DATETIME
)

--1
ALTER TABLE STUDENT_DETAIL
ADD CITY VARCHAR(20), BACKLOG INT

--2
ALTER TABLE STUDENT_DETAIL
ALTER COLUMN NAME VARCHAR(35)

--3
ALTER TABLE STUDENT_DETAIL
ALTER COLUMN CPI INT

--4
EXEC SP_RENAME 'STUDENT_DETAIL.ENROLLMENT_NO','ENO'

--5
ALTER TABLE STUDENT_DETAIL
DROP COLUMN CITY

--6
EXEC SP_RENAME 'STUDENT_DETAIL','STUDENT_MASTER'
