CREATE DATABASE CSE_3B_310

CREATE TABLE BRANCH
(
 BNAME VARCHAR(50),
 CITY VARCHAR(50)
 )

 INSERT INTO BRANCH(BNAME,CITY)
 VALUES
 ('VRCH','NAGPUR'),
 ('AJNI' ,'NAGPUR'),
 ('KAROLBAGH','DELHI'),
 ('CHANDI','DELHI'),
 ('DHARAMPETH','NAGPUR'),
 ('M.G.RODE','BANGLORE'),
 ('ANDHERI','BOMBAY'),
 ('VIRAR','BOMBAY'),
 ('NEHRU PLACE','DELHI'),
 ('POWAI','BOMBAY')
