CREATE DATABASE CSE_3B_310


-----A------


CREATE TABLE CRICKET
(
 NAME VARCHAR(50),
 CITY VARCHAR(50),
 AGE INT
 )

 INSERT INTO CRICKET (NAME,CITY,AGE)
 VALUES
 ('SACHIN TENDULKAR','MUMBAI',30),
 ('RAHUL DRAVID','BOMBAY',35),
 ('M.S.DHONI','JHARKHAND',31),
 ('SURESH RAINA','GUJARAT',30)

 ---1
 SELECT * INTO WORLDCUP FROM CRICKET

 SELECT * FROM WORLDCUP

 ---2
 SELECT NAME,CITY INTO T20 
 FROM CRICKET
 WHERE 1=0

---3
 SELECT * INTO IPL
 FROM CRICKET
 WHERE 1=0;



 -----------B--------------
 CREATE TABLE EMPLOYEE
(
 NAME VARCHAR(50),
 CITY VARCHAR(50),
 AGE INT
 )

 INSERT INTO EMPLOYEE(NAME,CITY,AGE)
 VALUES
 ('JAY PATEL','RAJKOT',30),
 ('RAHUL DAVE','BARODA',35),
 ('JEET PATEL','SURART',31),
 ('VIJAY RAVAL','RAJKOT',30)

 ---1
 SELECT * INTO EMPLOYEE_DETAIL FROM EMPLOYEE
  SELECT * FROM EMPLOYEE_DETAIL

  ---2
  SELECT NAME,CITY INTO  EMPLOYEE_DATA
  FROM EMPLOYEE
  WHERE 1=2

  SELECT * FROM EMPLOYEE_DATA

  ---3
  SELECT * INTO EMPLOYEE_INFO
  FROM EMPLOYEE
  WHERE 1=2

  SELECT * FROM EMPLOYEE_INFO


  ----------------------PART C--------------------------------------

  ---1
  INSERT  INTO EMPLOYEE_INFO
  SELECT * FROM EMPLOYEE
  WHERE CITY='RAJKOT'

  SELECT * FROM EMPLOYEE_INFO

  
---2
INSERT  INTO EMPLOYEE_INFO
 SELECT * FROM EMPLOYEE
 WHERE AGE>32

  SELECT * FROM EMPLOYEE_INFO
